services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: appsecret
      POSTGRES_DB: appdb
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build: .
    depends_on:
      - db
      - redis
    environment:
      DATABASE_DSN: postgres://appuser:appsecret@db:5432/appdb?sslmode=disable
      REDIS_ADDR: redis:6379
      REDIS_PASSWORD: ""
      JWT_SECRET: supersecret
      SMTP_HOST: smtp.example.com
      SMTP_PORT: 587
      SMTP_USER: your_email@example.com
      SMTP_PASS: your_email_password
    ports:
      - "8080:8080"

volumes:
  db_data:
  redis_data:
